### ISSUE TITLE
Properties with a value of inherit should not be merged

### ISSUE THREAD

**Issue by joebandenburg** [ben-eb/postcss-merge-longhand#18]
The merger needs to have a special case for `inherit` properties and should refuse to merge them.

Example:
```
h1 {
  border-width: 3px;
  border-style: solid;
  border-color: inherit;
}
```
The current version merges these rules, which results in:
```
h1{border:3px solid inherit}
```
This is not a valid property and is ignored by the latest Chrome and Firefox.

**Comment by ben-eb** [comment]
Released in `1.0.2`. Thanks for reporting. :+1:
