### ISSUE TITLE
Border Merging fails

### ISSUE THREAD

**Issue by apriljunge** [ben-eb/postcss-merge-longhand#26]
### This CSS input
```
.merge-longhand {
  border: 1px solid black;
  border-top-width: 2px;
  border-right-width: 2px;
  border-bottom-width: 2px;
}
```

### Results in this output
```
.merge-longhand {
  border: 2px solid black;
  border-left: solid black;
  border-width: 1px;
}
```

### This output is expected
```
.merge-longhand {
  border: solid black;
  border-width: 2px 2px 2px 1px;
}
```
It also happens with `border-xxx-color` or `border-xxx-style`, but only when three sides are defined.

**Comment by andyjansson** [comment]
@implico Have you tested this with `cssnano@next`?

**Comment by implico** [comment]
@andyjansson yes, to be exact: `cssnano@4.0.0-rc.2`. Does it have an impact?

**Comment by andyjansson** [comment]
Ok, I just checked with the latest release and I can confirm this is happening.

**Comment by andyjansson** [comment]
Closing these, as they should be fixed. You can verify here: https://cssnano.co/playground/
