### ISSUE TITLE
Support column merging

### ISSUE THREAD

**Issue by andyjansson** [ben-eb/postcss-merge-longhand#7]
These longhand properties need to be merged to a single `column` shorthand: 

* `column-width`
* `column-count`

Formal syntax:
```
<'column-width'> || <'column-count'>
```

**Comment by ben-eb** [comment]
`columns`. :+1: 

https://developer.mozilla.org/en-US/docs/Web/CSS/columns

**Comment by andyjansson** [comment]
Fixed in `refactor` branch.
